import { randomBytes, timingSafeEqual } from "node:crypto";
import type { Prisma, PrismaClient } from "@sla/db";
import { ZendeskClient } from "./client";
import type { ZendeskOAuthConfig } from "./oauth";
import { mapAuditToRawEvent, mapTicketToRawEvent, type RawEventInput } from "./rawEvents";
import { loadFreshZendeskCredentials, refreshAfterUnauthorized } from "./tokenLifecycle";

/** Random per-integration secret, generated once at connect and never rotated on reconnect (see Integration.webhookSecret's doc comment). */
export function generateWebhookSecret(): string {
  return randomBytes(24).toString("hex");
}

/**
 * Zendesk's own webhook signing secret can't be used here: it's generated by
 * Zendesk *after* a webhook is created, with no field anywhere in the
 * creation form to hand Zendesk one of our own choosing — so HMAC request
 * signing (which needs a secret both sides agree on in advance) isn't
 * actually available to us. What the creation form's Authentication dropdown
 * does offer is "Bearer token", where the customer pastes a token of their
 * choice and Zendesk sends it back as `Authorization: Bearer <token>` on
 * every call. Verification here is a constant-time compare against that
 * header, using this integration's `webhookSecret` as the token — the same
 * shared-secret model as Jira's `?secret=` query parameter, just carried in
 * a header instead of the URL.
 */
export function verifyZendeskWebhookSecret(expected: string, authorizationHeader: string | null): boolean {
  const match = authorizationHeader ? /^Bearer (.+)$/.exec(authorizationHeader) : null;
  const provided = match?.[1];
  if (!provided) return false;

  const expectedBuffer = Buffer.from(expected);
  const providedBuffer = Buffer.from(provided);
  // timingSafeEqual throws on mismatched lengths rather than returning false.
  if (expectedBuffer.length !== providedBuffer.length) return false;
  return timingSafeEqual(expectedBuffer, providedBuffer);
}

/**
 * The webhook payload shape is whatever the customer's Zendesk trigger/event
 * subscription is configured to send, not a shape we control — this reads a
 * ticket id leniently from the handful of shapes Zendesk's admin UI actually
 * offers: a custom trigger body of `{"ticket_id": "{{ticket.id}}"}` (what the
 * settings page instructs customers to configure), or a native "Ticket
 * Events" subscription's `{"detail": {"id": ...}, ...}"` / `{"ticket": {...}}`
 * envelope.
 */
export function extractZendeskWebhookTicketId(payload: unknown): number | null {
  if (payload === null || typeof payload !== "object") return null;
  const body = payload as Record<string, unknown>;
  const ticket = body.ticket as Record<string, unknown> | undefined;
  const detail = body.detail as Record<string, unknown> | undefined;
  const candidate = body.ticket_id ?? ticket?.id ?? detail?.id ?? body.id;
  const id = typeof candidate === "string" ? Number(candidate) : candidate;
  return typeof id === "number" && Number.isInteger(id) && id > 0 ? id : null;
}

export interface WebhookIngestResult {
  ticketsFetched: number;
  ticketAuditsFetched: number;
}

/**
 * Targeted refetch of one ticket, triggered by an inbound webhook (roadmap
 * step 20) rather than the incremental export the two-speed poller uses.
 * Deliberately never touches Integration.cursor: that watermark belongs to
 * the incremental-export stream `runZendeskBackfill` advances, and a
 * single-ticket refetch must not perturb it. Writes land through the same
 * RawEvent mapping functions the poller uses, so the next
 * `runZendeskNormalization` call — poll-driven or webhook-driven — picks
 * them up identically either way.
 */
export async function runZendeskWebhookIngest(
  prisma: PrismaClient,
  integrationId: string,
  config: ZendeskOAuthConfig,
  ticketId: number,
): Promise<WebhookIngestResult> {
  const credentials = await loadFreshZendeskCredentials(prisma, integrationId, config);
  const client = new ZendeskClient(credentials, {
    onUnauthorized: (failed) => refreshAfterUnauthorized(prisma, integrationId, config, failed),
  });

  const { ticket } = await client.fetchTicket(ticketId);
  const rawEvents: RawEventInput[] = [mapTicketToRawEvent(ticket)];

  let ticketAuditsFetched = 0;
  let nextPageUrl: string | undefined;
  for (;;) {
    const page = await client.fetchTicketAuditsPage(ticketId, nextPageUrl);
    rawEvents.push(...page.audits.map(mapAuditToRawEvent));
    ticketAuditsFetched += page.audits.length;
    if (!page.next_page) break;
    nextPageUrl = page.next_page;
  }

  await prisma.rawEvent.createMany({
    data: rawEvents.map((input) => ({
      integrationId,
      providerEventId: input.providerEventId,
      sourceHash: input.sourceHash,
      payload: input.payload as Prisma.InputJsonValue,
    })),
    skipDuplicates: true,
  });

  return { ticketsFetched: 1, ticketAuditsFetched };
}
