import type { AtRiskRowData } from "@/lib/types/at-risk";

export const AT_RISK_DUMMY_DATA: AtRiskRowData[] = [
  {
    commitmentId: "commit-001",
    caseId: "case-001",
    externalId: "CS-10482",
    subject: "Production API returning intermittent 500 errors",
    customerName: "Acme Corporation",
    requesterName: "Omar Hassan",
    kind: "resolution",
    remainingMinutes: 32,
    status: "at_risk",
    currentLeg: "engineering",
    minutesInCurrentLeg: 118,
    priority: "urgent",
    tier: "Enterprise",
    targetMinutes: 240,
    elapsedSeconds: 12480,
    supportLegMinutes: 42,
    engineeringLegMinutes: 118,
    supportAssigneeName: "Yasser Alnajjar",
    linkedIssue: {
      system: "jira",
      externalId: "ENG-4821",
      confidence: "certain",
    },
  },

  {
    commitmentId: "commit-002",
    caseId: "case-002",
    externalId: "CS-10479",
    subject: "SSO login fails for newly provisioned users",
    customerName: "Northstar Financial",
    requesterName: "Mariam Adel",
    kind: "resolution",
    remainingMinutes: 74,
    status: "at_risk",
    currentLeg: "engineering",
    minutesInCurrentLeg: 86,
    priority: "high",
    tier: "Enterprise",
    targetMinutes: 240,
    elapsedSeconds: 9960,
    supportLegMinutes: 38,
    engineeringLegMinutes: 86,
    supportAssigneeName: "Ahmed Khaled",
    linkedIssue: {
      system: "linear",
      externalId: "LIN-928",
      confidence: "probable",
    },
  },

  {
    commitmentId: "commit-003",
    caseId: "case-003",
    externalId: "CS-10461",
    subject: "Customer unable to export monthly billing report",
    customerName: "Vertex Labs",
    requesterName: "Salma Nabil",
    kind: "resolution",
    remainingMinutes: 126,
    status: "at_risk",
    currentLeg: "support",
    minutesInCurrentLeg: 51,
    priority: "normal",
    tier: "Growth",
    targetMinutes: 360,
    elapsedSeconds: 14040,
    supportLegMinutes: 51,
    engineeringLegMinutes: 74,
    supportAssigneeName: "Mina George",
    linkedIssue: null,
  },

  {
    commitmentId: "commit-004",
    caseId: "case-004",
    externalId: "CS-10455",
    subject: "Webhook delivery delayed for payment events",
    customerName: "Atlas Commerce",
    requesterName: "Karim Mostafa",
    kind: "first_response",
    remainingMinutes: 168,
    status: "on_track",
    currentLeg: "engineering",
    minutesInCurrentLeg: 64,
    priority: "high",
    tier: "Enterprise",
    targetMinutes: 480,
    elapsedSeconds: 18720,
    supportLegMinutes: 72,
    engineeringLegMinutes: 64,
    supportAssigneeName: "Nour Hassan",
    linkedIssue: {
      system: "github",
      externalId: "GH-7712",
      confidence: "certain",
    },
  },

  {
    commitmentId: "commit-005",
    caseId: "case-005",
    externalId: "CS-10442",
    subject: "Incorrect timezone shown in scheduled reports",
    customerName: "BrightPath Education",
    requesterName: "Laila Samir",
    kind: "resolution",
    remainingMinutes: 214,
    status: "on_track",
    currentLeg: "waiting_customer",
    minutesInCurrentLeg: 143,
    priority: "normal",
    tier: "Standard",
    targetMinutes: 480,
    elapsedSeconds: 15960,
    supportLegMinutes: 88,
    engineeringLegMinutes: 54,
    supportAssigneeName: "Mahmoud Ali",
    linkedIssue: null,
  },

  {
    commitmentId: "commit-006",
    caseId: "case-006",
    externalId: "CS-10431",
    subject: "Mobile application crashes after latest update",
    customerName: "Cairo Logistics",
    requesterName: "Hany Ibrahim",
    kind: "resolution",
    remainingMinutes: -48,
    status: "breached",
    currentLeg: "engineering",
    minutesInCurrentLeg: 201,
    priority: "critical",
    tier: "Enterprise",
    targetMinutes: 240,
    elapsedSeconds: 17280,
    supportLegMinutes: 61,
    engineeringLegMinutes: 201,
    supportAssigneeName: "Yasser Alnajjar",
    linkedIssue: {
      system: "jira",
      externalId: "ENG-4763",
      confidence: "certain",
    },
  },

  {
    commitmentId: "commit-007",
    caseId: "case-007",
    externalId: "CS-10418",
    subject: "Unable to reset account password",
    customerName: "Delta Healthcare",
    requesterName: "Ahmed Fathy",
    kind: "first_response",
    remainingMinutes: -132,
    status: "breached",
    currentLeg: "support",
    minutesInCurrentLeg: 297,
    priority: "high",
    tier: "Enterprise",
    targetMinutes: 120,
    elapsedSeconds: 15120,
    supportLegMinutes: 297,
    engineeringLegMinutes: 0,
    supportAssigneeName: "Sara Mohamed",
    linkedIssue: null,
  },

  {
    commitmentId: "commit-008",
    caseId: "case-008",
    externalId: "CS-10398",
    subject: "Data synchronization stopped overnight",
    customerName: "Orbit Systems",
    requesterName: "Tarek Mahmoud",
    kind: "resolution",
    remainingMinutes: 44,
    status: "at_risk",
    currentLeg: "engineering",
    minutesInCurrentLeg: 152,
    priority: "critical",
    tier: "Enterprise",
    targetMinutes: 360,
    elapsedSeconds: 18960,
    supportLegMinutes: 46,
    engineeringLegMinutes: 152,
    supportAssigneeName: "Omar Khaled",
    linkedIssue: {
      system: "linear",
      externalId: "LIN-901",
      confidence: "certain",
    },
  },

  {
    commitmentId: "commit-009",
    caseId: "case-009",
    externalId: "CS-10376",
    subject: "Invoice PDF generated with missing line items",
    customerName: "Greenfield Retail",
    requesterName: "Nada Hassan",
    kind: "resolution",
    remainingMinutes: 98,
    status: "at_risk",
    currentLeg: "support",
    minutesInCurrentLeg: 73,
    priority: "normal",
    tier: "Growth",
    targetMinutes: 240,
    elapsedSeconds: 8520,
    supportLegMinutes: 73,
    engineeringLegMinutes: 0,
    supportAssigneeName: null,
    linkedIssue: null,
  },

  {
    commitmentId: "commit-010",
    caseId: "case-010",
    externalId: "CS-10354",
    subject: "Dashboard widgets are not loading",
    customerName: "Pioneer Media",
    requesterName: "Mostafa Saeed",
    kind: "first_response",
    remainingMinutes: 286,
    status: "on_track",
    currentLeg: "support",
    minutesInCurrentLeg: 34,
    priority: "low",
    tier: "Standard",
    targetMinutes: 480,
    elapsedSeconds: 11640,
    supportLegMinutes: 34,
    engineeringLegMinutes: 0,
    supportAssigneeName: "Heba Ali",
    linkedIssue: null,
  },

  {
    commitmentId: "commit-011",
    caseId: "case-011",
    externalId: "CS-10321",
    subject: "Customer reports duplicate notifications",
    customerName: "Summit Travel",
    requesterName: null,
    kind: "resolution",
    remainingMinutes: 52,
    status: "at_risk",
    currentLeg: "waiting_customer",
    minutesInCurrentLeg: 97,
    priority: "high",
    tier: "Growth",
    targetMinutes: 240,
    elapsedSeconds: 11280,
    supportLegMinutes: 64,
    engineeringLegMinutes: 42,
    supportAssigneeName: "Amr Youssef",
    linkedIssue: {
      system: "github",
      externalId: "GH-7621",
      confidence: "probable",
    },
  },

  {
    commitmentId: "commit-012",
    caseId: "case-012",
    externalId: "CS-10298",
    subject: "Legacy integration returns invalid payload",
    customerName: "Meridian Group",
    requesterName: "Rana Tarek",
    kind: "resolution",
    remainingMinutes: 132,
    status: "at_risk",
    currentLeg: "engineering",
    minutesInCurrentLeg: 109,
    priority: "normal",
    tier: "Standard",
    targetMinutes: 360,
    elapsedSeconds: 13680,
    supportLegMinutes: 57,
    engineeringLegMinutes: 109,
    supportAssigneeName: "Khaled Sameh",
    linkedIssue: {
      system: "jira",
      externalId: "ENG-4618",
      confidence: "certain",
    },
  },

  {
    commitmentId: "commit-013",
    caseId: "case-013",
    externalId: "CS-10274",
    subject: "User permissions not reflected immediately",
    customerName: "Cedar Technologies",
    requesterName: "Yousef Ali",
    kind: "first_response",
    remainingMinutes: 360,
    status: "on_track",
    currentLeg: "unknown",
    minutesInCurrentLeg: 12,
    priority: "low",
    tier: "Standard",
    targetMinutes: 480,
    elapsedSeconds: 7200,
    supportLegMinutes: 0,
    engineeringLegMinutes: 0,
    supportAssigneeName: null,
    linkedIssue: null,
  },

  {
    commitmentId: "commit-014",
    caseId: "case-014",
    externalId: "CS-10251",
    subject: "Critical production deployment blocked",
    customerName: "Global Freight",
    requesterName: "Ibrahim Essam",
    kind: "resolution",
    remainingMinutes: 18,
    status: "at_risk",
    currentLeg: "engineering",
    minutesInCurrentLeg: 224,
    priority: "urgent",
    tier: "Enterprise",
    targetMinutes: 240,
    elapsedSeconds: 13320,
    supportLegMinutes: 18,
    engineeringLegMinutes: 224,
    supportAssigneeName: "Yasser Alnajjar",
    linkedIssue: {
      system: "jira",
      externalId: "ENG-4590",
      confidence: "certain",
    },
  },

  {
    commitmentId: "commit-015",
    caseId: "case-015",
    externalId: "CS-10212",
    subject: "Request for historical audit export",
    customerName: "BluePeak Consulting",
    requesterName: "Dina Ahmed",
    kind: "resolution",
    remainingMinutes: 780,
    status: "on_track",
    currentLeg: "support",
    minutesInCurrentLeg: 21,
    priority: "low",
    tier: "Standard",
    targetMinutes: 960,
    elapsedSeconds: 10800,
    supportLegMinutes: 21,
    engineeringLegMinutes: 0,
    supportAssigneeName: "Hossam Adel",
    linkedIssue: null,
  },

  {
    commitmentId: "commit-016",
    caseId: "case-016",
    externalId: "CS-10188",
    subject: "Integration credentials rejected after rotation",
    customerName: "Redline Manufacturing",
    requesterName: "George Hanna",
    kind: "resolution",
    remainingMinutes: 83,
    status: "at_risk",
    currentLeg: "engineering",
    minutesInCurrentLeg: 91,
    priority: "high",
    tier: "Enterprise",
    targetMinutes: 240,
    elapsedSeconds: 9420,
    supportLegMinutes: 44,
    engineeringLegMinutes: 91,
    supportAssigneeName: "Mariam Adel",
    linkedIssue: {
      system: "linear",
      externalId: "LIN-874",
      confidence: "probable",
    },
  },

  {
    commitmentId: "commit-017",
    caseId: "case-017",
    externalId: "CS-10162",
    subject: "Search results missing recent records",
    customerName: "Nova Analytics",
    requesterName: "Fady Nabil",
    kind: "resolution",
    remainingMinutes: 147,
    status: "at_risk",
    currentLeg: "support",
    minutesInCurrentLeg: 58,
    priority: "normal",
    tier: "Growth",
    targetMinutes: 360,
    elapsedSeconds: 12780,
    supportLegMinutes: 58,
    engineeringLegMinutes: 0,
    supportAssigneeName: "Ahmed Khaled",
    linkedIssue: null,
  },

  {
    commitmentId: "commit-018",
    caseId: "case-018",
    externalId: "CS-10121",
    subject: "Billing subscription unexpectedly suspended",
    customerName: "EastBridge Solutions",
    requesterName: "Mai Ehab",
    kind: "first_response",
    remainingMinutes: -24,
    status: "breached",
    currentLeg: "waiting_customer",
    minutesInCurrentLeg: 174,
    priority: "high",
    tier: "Enterprise",
    targetMinutes: 120,
    elapsedSeconds: 8640,
    supportLegMinutes: 94,
    engineeringLegMinutes: 0,
    supportAssigneeName: "Nour Hassan",
    linkedIssue: null,
  },
];
