import { NextResponse } from "next/server";
import {
  extractZendeskWebhookTicketId,
  runZendeskNormalization,
  runZendeskWebhookIngest,
  verifyZendeskWebhookSecret,
  ZendeskApiError,
  ZendeskReauthRequiredError,
} from "@sla/zendesk";
import { getPrismaClient } from "@sla/db";
import { getZendeskOAuthConfig } from "@/lib/zendesk-env";
import { runWebhookPipelineTail } from "@/lib/webhook-pipeline";

export const maxDuration = 60;

/**
 * Zendesk webhook receiver (roadmap step 20). Unauthenticated by session —
 * Zendesk calls this directly — so authenticity rests on a shared secret.
 * Zendesk's own webhook signing secret isn't usable here: it's generated by
 * Zendesk only after the webhook is created, with no field in the creation
 * form to hand it one of our own choosing. What the creation form's
 * Authentication dropdown does offer is "Bearer token", so customers paste
 * this integration's secret there and Zendesk sends it back as
 * `Authorization: Bearer <token>` on every call.
 *
 * On success this runs the full poll-cycle tail (ingest → normalize →
 * commitments → evaluation → notifications) for one ticket, synchronously,
 * which is what actually delivers "real-time freshness" — the 5-minute
 * active-set poll and 60-minute reconciliation sweep (roadmap step 7) keep
 * running unchanged as the safety net for missed or out-of-order deliveries.
 */
export async function POST(request: Request, { params }: { params: Promise<{ integrationId: string }> }) {
  const { integrationId } = await params;
  const prisma = getPrismaClient();

  const integration = await prisma.integration.findUnique({ where: { id: integrationId } });
  if (!integration || integration.provider !== "zendesk" || !integration.webhookSecret) {
    return NextResponse.json({ error: "Unknown webhook endpoint" }, { status: 404 });
  }

  if (!verifyZendeskWebhookSecret(integration.webhookSecret, request.headers.get("authorization"))) {
    return NextResponse.json({ error: "Invalid webhook credentials" }, { status: 401 });
  }

  // A disconnected integration has no credentials to ingest with — accept
  // the delivery (so the customer's Zendesk instance doesn't see it as
  // failing and retry forever) but do nothing with it.
  if (integration.status === "disconnected") {
    return NextResponse.json({ status: "ignored", reason: "integration disconnected" });
  }

  let payload: unknown;
  try {
    payload = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const ticketId = extractZendeskWebhookTicketId(payload);
  if (ticketId === null) {
    return NextResponse.json({ error: "No ticket id found in webhook payload" }, { status: 400 });
  }

  let config;
  try {
    config = await getZendeskOAuthConfig(integration.organizationId);
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Zendesk OAuth is not configured" },
      { status: 500 },
    );
  }

  try {
    await runZendeskWebhookIngest(prisma, integration.id, config, ticketId);
    await runZendeskNormalization(prisma, integration.id);
    const pipeline = await runWebhookPipelineTail(prisma, integration.organizationId);

    await prisma.integration.update({
      where: { id: integration.id },
      data: { lastSyncAt: new Date(), lastSyncError: null },
    });

    return NextResponse.json({ status: "processed", ticketId, ...pipeline });
  } catch (error) {
    // A ticket the incremental export listed but that 404s on direct fetch
    // (merged away, permanently deleted) is a normal occurrence, not a
    // failure to retry — mirrors runZendeskBackfill's own handling.
    if (error instanceof ZendeskApiError && error.status === 404) {
      return NextResponse.json({ status: "ignored", reason: "ticket not found" });
    }

    if (error instanceof ZendeskReauthRequiredError) {
      await prisma.integration.update({
        where: { id: integration.id },
        data: { status: "reauth_required", lastSyncAt: new Date(), lastSyncError: "Zendesk needs to be reconnected" },
      });
      // Accepted, not retried: reconnecting requires a human, which no
      // number of Zendesk retries will produce.
      return NextResponse.json({ status: "ignored", reason: "reauth required" });
    }

    const message = error instanceof Error ? error.message : String(error);
    await prisma.integration.update({
      where: { id: integration.id },
      data: { lastSyncAt: new Date(), lastSyncError: message },
    });
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
